### ISSUE TITLE
Support nest Http request logging

### ISSUE THREAD

**Issue by narimanam** [jukkahell/nestlogger#11]
Hi, 
Thanks for this great library.
I hope if I can use LoggerService as an Interceptor for logging incoming Http Requests. Is there any built-in functionality for that purpose?
something like morgan

**Comment by jukkahell** [comment]
Hey, thanks!

Do you mean something like this: https://github.com/jukkahell/nestlogger/blob/master/lib/logging/logger.interceptor.ts ?
Then use it in your main.ts (I dropped out the httpService injection on purpose here):
```
import { LoggerService } from "nest-logger";
...
const logger = app.get<LoggerService>(LoggerService);
app.useGlobalIterceptors(new LoggerInterceptor(logger));
```

If you had something more special in mind, I would be happy to hear it out.

Edit: Oh, and you should create your own interceptor for your own logic. This one is for injecting a request-id header in http calls and every log entry. It was meant to keep track of a single request in an environment with multiple microservices. But I guess it didn't work that good so that's why I've left it out of the documentation too.

**Comment by narimanam** [comment]
Thanks,
I wrote my custom interceptor specifically for handling `request-id` and `response-time` with the usage of `on-finished` express library.
